In [4]:
from datetime import datetime

def Liberary(user_name, book_name, borrow_date, return_date , Due_date):

    borrow_date = datetime.strptime(borrow_date, "%d-%m-%Y")
    Due_date = datetime.strptime(Due_date,"%d-%m-%Y")
    return_date = datetime.strptime(return_date, "%d-%m-%Y") if return_date else None

    if return_date:
      if borrow_date < return_date:
        print(f"{user_name}, {book_name}, {borrow_date}, {return_date} (returned on time)")
      else:
        print(f"{user_name}, {book_name}, {borrow_date}, {return_date}  (returned late)")
    else:
      print(f" {user_name}, {book_name}, {Due_date} or not returned??")

Liberary("Muzamil", "Python Book", "10-08-2025", "24-08-2025", "25-08-2025")
Liberary("Muzamil", "Python Book", "10-08-2025", None, "24-08-2025")
Liberary("Muzamil", "Python Book", "10-08-2025", "30-08-2025", "25-08-2025")




Muzamil, Python Book, 2025-08-10 00:00:00, 2025-08-24 00:00:00 (returned on time)
 Muzamil, Python Book, 2025-08-24 00:00:00 or not returned??
Muzamil, Python Book, 2025-08-10 00:00:00, 2025-08-30 00:00:00 (returned on time)


In [5]:
import numpy as np

np.array([[1,2,3], [4,5,6] , [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
my_random_number = np.random.random(3)

my_random_number

array([0.08610731, 0.98084742, 0.65272669])

In [ ]:
my_random_number[0:2,0]

array([0.97419945, 0.48579179])

In [ ]:
x = 6
print(x)

y = x
print(y)

x = 10
print(x)
print(y)

6
6
10
6
